### ISSUE TITLE
Deprecation warnings in Mendix 7.13

### ISSUE THREAD

**Issue by recktenwaldfabian** [mendix/OnchangeInputbox#6]
Getting these warnings:
DEPRECATED: mx.data.save will be removed in version 8.0. The 'mx.data.save' function does not have any effect anymore. MxObjects are now automatically saved as part of 'mx.data.commit', 'mx.data.rollback', 'mx.data.action' and 'mx.data.saveDocument'

**Comment by Stanley-Okwii** [comment]
Hello @recktenwaldfabian ,

Thanks for raising this issue. We will look into it and get back to you as soon as possible.

Cheers,
Stanley
